Struktura folderów
LucasHamera/raytracer.cs pull request #69
Opened 2020-07-28 21:10 UTC by LucasHamera

2020-07-28 21:14 UTC, darksv requested changes

2020-07-28 21:14 UTC, darksv commented on tests/RayTracer.Geometry.Tests/BaselineTests.cs
> +            var newColor = Raytracer.Geometry.Geometries.Geometry.Scale(scale, c);
może dodać using?

2020-07-28 21:14 UTC, darksv commented on tests/RayTracer.Geometry.Tests/BaselineTests.cs
> +            var w = Raytracer.Geometry.Geometries.Geometry.Cross(u, v);
może dodać using?

2020-07-28 21:14 UTC, darksv commented on tests/RayTracer.Geometry.Tests/BaselineTests.cs
> +            var result = Raytracer.Geometry.Geometries.Geometry.Norm(v);
może dodać using?

2020-07-28 21:14 UTC, darksv commented on tests/RayTracer.Geometry.Tests/BaselineTests.cs
> +            Raytracer.Geometry.Geometries.Geometry.Mag(v).Should().BeApproximately(expected, Precision);
może dodać using?

2020-07-28 21:14 UTC, darksv commented on tests/RayTracer.Geometry.Tests/BaselineTests.cs
> +            Raytracer.Geometry.Geometries.Geometry.Dot(u, v).Should().BeApproximately(expected, Precision);
może dodać using?

2020-07-28 21:14 UTC, darksv commented on tests/RayTracer.Geometry.Tests/BaselineTests.cs
> +            Raytracer.Geometry.Geometries.Geometry.Clamp(value, min, max).Should().BeApproximately(expected, Precision);
może dodać using?

2020-07-28 21:14 UTC, darksv commented on tests/RayTracer.Geometry.Tests/BaselineTests.cs
> +            Raytracer.Geometry.Geometries.Geometry.Floor(x).Should().BeApproximately(expected, Precision);
może dodać using?

2020-07-28 21:14 UTC, darksv commented on tests/RayTracer.Geometry.Tests/BaselineTests.cs
> +            Raytracer.Geometry.Geometries.Geometry.Pow(@base, exp).Should().BeApproximately(expected, Precision);
może dodać using?

2020-07-28 21:14 UTC, darksv commented on tests/RayTracer.Geometry.Tests/BaselineTests.cs
> +            Raytracer.Geometry.Geometries.Geometry.Sqrt(x).Should().BeApproximately(expected, Precision);
może dodać using?

2020-07-29 07:52 UTC, LucasHamera commented on tests/RayTracer.Geometry.Tests/BaselineTests.cs
> +            var newColor = Raytracer.Geometry.Geometries.Geometry.Scale(scale, c);
Dodam, resparperem zmieniałem i nawet nie skontrolowałem :)

2020-07-29 16:32 UTC, LucasHamera commented on src/Raytracer.Geometry/Geometries/GeometryMath.cs
> +    public static class GeometryMath
Musiałem zmienić nazwę, gdyż projekt gryzło się to i nie dało się przez using

2020-07-29 18:52 UTC, darksv approved these changes

2020-07-29 18:59 UTC, merged